-- DF95_PluginMetaInspector_ImGui.lua
-- Simple ImGui-based inspector for DF95_PluginMetaDomain
-- Lets you browse, filter and override category / idm_group for each FX.

local r = reaper

-- Check ReaImGui availability
if not r.ImGui_CreateContext then
  r.ShowMessageBox("ReaImGui is not installed or not enabled.\n\nPlease install 'ReaImGui: Dear ImGui integration' via ReaPack.", "DF95 PluginMeta Inspector", 0)
  return
end

-- Load DF95_PluginMetaDomain
local function load_plugin_meta_domain()
  local res_path = r.GetResourcePath()
  local path = res_path .. "/Scripts/IFLS/DF95/DF95_PluginMetaDomain.lua"
  local ok, mod = pcall(dofile, path)
  if not ok then
    r.ShowMessageBox("Could not load DF95_PluginMetaDomain.lua:\n" .. tostring(mod), "DF95 PluginMeta Inspector", 0)
    return nil
  end
  return mod
end

local DF95 = load_plugin_meta_domain()
if not DF95 then return end

-- Load overrides file if present
local function load_overrides()
  local res_path = r.GetResourcePath()
  local path = res_path .. "/Scripts/IFLS/DF95/DF95_PluginMetaOverrides.lua"
  local ok, chunk = pcall(dofile, path)
  if not ok or type(chunk) ~= "table" then
    return {}
  end
  local ov = chunk.OVERRIDES or chunk.overrides or chunk
  if type(ov) ~= "table" then ov = {} end
  return ov
end

local function save_overrides(overrides)
  local res_path = r.GetResourcePath()
  local path = res_path .. "/Scripts/IFLS/DF95/DF95_PluginMetaOverrides.lua"
  local lines = {}
  table.insert(lines, "-- Auto-generated by DF95_PluginMetaInspector_ImGui.lua")
  table.insert(lines, "local M = {}")
  table.insert(lines, "M.OVERRIDES = {")
  for name, ov in pairs(overrides) do
    local name_esc = name:gsub("\\", "\\\\"):gsub("\"", "\\\"")
    local cat = ov.category or ""
    local grp = ov.idm_group or ""
    local cat_esc = cat:gsub("\\", "\\\\"):gsub("\"", "\\\"")
    local grp_esc = grp:gsub("\\", "\\\\"):gsub("\"", "\\\"")
    table.insert(lines, string.format('  ["%s"] = { category = "%s", idm_group = "%s" },', name_esc, cat_esc, grp_esc))
  end
  table.insert(lines, "}")
  table.insert(lines, "return M")
  local f = io.open(path, "w")
  if f then
    f:write(table.concat(lines, "\n"))
    f:close()
  else
    r.ShowMessageBox("Could not write overrides file:\n" .. path, "DF95 PluginMeta Inspector", 0)
  end
end

-- Build flat list from PLUGIN_META
local function build_fx_list()
  local fx_list = {}
  local meta = DF95.get_all and DF95.get_all() or DF95.PLUGIN_META or DF95.PluginMeta or {}
  for name, m in pairs(meta) do
    table.insert(fx_list, {
      name = name,
      id = m.id or "",
      vendor = m.vendor or "",
      category = m.category or "other",
      idm_group = m.idm_group or "IDM_MISC",
    })
  end
  table.sort(fx_list, function(a,b) return a.name:lower() < b.name:lower() end)
  return fx_list
end

local overrides = load_overrides()
local fx_list = build_fx_list()

-- ImGui setup
local ctx = r.ImGui_CreateContext("DF95 PluginMeta Inspector")
local io = r.ImGui_GetIO(ctx)
local font = r.ImGui_CreateFont("sans-serif", 14)
r.ImGui_Attach(ctx, font)

local filter_text = ""
local category_filter = "all"
local idm_filter = "all"
local selected_index = -1
local dirty = false

local categories = {
  "all",
  "dynamics",
  "saturation",
  "reverb",
  "delay",
  "modulation",
  "filter_eq",
  "console_tape",
  "meter_utility",
  "instrument",
  "texture_experimental",
  "midi",
  "other",
}

local idm_groups = {
  "all",
  "IDM_GLITCH",
  "IDM_SPACE",
  "IDM_ECHO",
  "IDM_STEREO",
  "IDM_TONE",
  "IDM_BUSS",
  "IDM_UTILITY",
  "IDM_INSTR",
  "IDM_TEXTURE",
  "IDM_MIDI",
  "IDM_MISC",
}

local function combo_enum(label, current, items)
  if r.ImGui_BeginCombo(ctx, label, current) then
    for _, v in ipairs(items) do
      local sel = (v == current)
      if r.ImGui_Selectable(ctx, v, sel) then
        current = v
      end
      if sel then
        r.ImGui_SetItemDefaultFocus(ctx)
      end
    end
    r.ImGui_EndCombo(ctx)
  end
  return current
end

local function passes_filter(entry)
  if category_filter ~= "all" and entry.category ~= category_filter then
    return false
  end
  if idm_filter ~= "all" and entry.idm_group ~= idm_filter then
    return false
  end
  if filter_text ~= nil and filter_text ~= "" then
    local s = filter_text:lower()
    local name = entry.name:lower()
    local vendor = entry.vendor:lower()
    if not (name:find(s, 1, true) or vendor:find(s, 1, true)) then
      return false
    end
  end
  return true
end

local function refresh_fx_list()
  -- reload DF95 meta (to get applied overrides)
  DF95 = load_plugin_meta_domain() or DF95
  fx_list = build_fx_list()
  selected_index = -1
end

local function loop()
  r.ImGui_SetCurrentContext(ctx)

  local visible, open = r.ImGui_Begin(ctx, "DF95 PluginMeta Inspector", true,
    r.ImGui_WindowFlags_MenuBar())

  if visible then
    if r.ImGui_BeginMenuBar(ctx) then
      if r.ImGui_BeginMenu(ctx, "File") then
        if r.ImGui_MenuItem(ctx, "Reload Meta") then
          refresh_fx_list()
        end
        if r.ImGui_MenuItem(ctx, "Save Overrides", nil, false, dirty) then
          save_overrides(overrides)
          dirty = false
          refresh_fx_list()
        end
        r.ImGui_EndMenu(ctx)
      end
      r.ImGui_EndMenuBar(ctx)
    end

    -- Top controls: filter + combo boxes
    r.ImGui_Text(ctx, "Filter:")
    r.ImGui_SameLine(ctx)
    local changed
    changed, filter_text = r.ImGui_InputText(ctx, "##filter", filter_text or "", r.ImGui_InputTextFlags_AutoSelectAll())
    r.ImGui_SameLine(ctx)
    r.ImGui_Text(ctx, "Category:")
    r.ImGui_SameLine(ctx)
    category_filter = combo_enum("##cat", category_filter, categories)
    r.ImGui_SameLine(ctx)
    r.ImGui_Text(ctx, "IDM Group:")
    r.ImGui_SameLine(ctx)
    idm_filter = combo_enum("##idm", idm_filter, idm_groups)

    r.ImGui_Separator(ctx)

    -- Left: list of FX
    local left_w = r.ImGui_GetWindowWidth(ctx) * 0.55
    r.ImGui_BeginChild(ctx, "##fxlist", left_w, 0, true)

    if r.ImGui_BeginTable(ctx, "FXTable", 3,
        r.ImGui_TableFlags_RowBg() | r.ImGui_TableFlags_Resizable() | r.ImGui_TableFlags_ScrollY()) then

      r.ImGui_TableSetupColumn(ctx, "Name")
      r.ImGui_TableSetupColumn(ctx, "Vendor")
      r.ImGui_TableSetupColumn(ctx, "Category / IDM")
      r.ImGui_TableHeadersRow(ctx)

      for i, entry in ipairs(fx_list) do
        if passes_filter(entry) then
          r.ImGui_TableNextRow(ctx)
          r.ImGui_TableNextColumn(ctx)
          local is_selected = (i == selected_index)
          if r.ImGui_Selectable(ctx, entry.name, is_selected, r.ImGui_SelectableFlags_SpanAllColumns()) then
            selected_index = i
          end

          r.ImGui_TableNextColumn(ctx)
          r.ImGui_Text(ctx, entry.vendor ~= "" and entry.vendor or "-")

          r.ImGui_TableNextColumn(ctx)
          r.ImGui_Text(ctx, string.format("%s / %s", entry.category, entry.idm_group))
        end
      end

      r.ImGui_EndTable(ctx)
    end

    r.ImGui_EndChild(ctx)

    -- Right: details of selected FX
    r.ImGui_SameLine(ctx)
    r.ImGui_BeginChild(ctx, "##details", 0, 0, true)

    if selected_index > 0 and fx_list[selected_index] then
      local fx = fx_list[selected_index]
      r.ImGui_Text(ctx, "Selected FX:")
      r.ImGui_Separator(ctx)
      r.ImGui_Text(ctx, fx.name)
      r.ImGui_Text(ctx, "Vendor: " .. (fx.vendor ~= "" and fx.vendor or "-"))
      r.ImGui_Text(ctx, "ID: " .. (fx.id ~= "" and fx.id or "-"))
      r.ImGui_Separator(ctx)

      local current_cat = fx.category
      local current_idm = fx.idm_group

      r.ImGui_Text(ctx, "Category:")
      current_cat = combo_enum("##detail_cat", current_cat, categories)
      r.ImGui_Text(ctx, "IDM Group:")
      current_idm = combo_enum("##detail_idm", current_idm, idm_groups)

      if current_cat ~= fx.category or current_idm ~= fx.idm_group then
        if r.ImGui_Button(ctx, "Queue Override") then
          overrides[fx.name] = {
            category = (current_cat ~= "all" and current_cat or fx.category),
            idm_group = (current_idm ~= "all" and current_idm or fx.idm_group),
          }
          fx.category = overrides[fx.name].category
          fx.idm_group = overrides[fx.name].idm_group
          dirty = true
        end
        r.ImGui_SameLine(ctx)
        r.ImGui_Text(ctx, "(Will be saved to DF95_PluginMetaOverrides.lua)")
      else
        r.ImGui_Text(ctx, "No changes pending for this FX.")
      end

      if overrides[fx.name] then
        r.ImGui_Separator(ctx)
        r.ImGui_Text(ctx, "Existing Override:")
        r.ImGui_Text(ctx, "Category: " .. tostring(overrides[fx.name].category))
        r.ImGui_Text(ctx, "IDM Group: " .. tostring(overrides[fx.name].idm_group))
        if r.ImGui_Button(ctx, "Remove Override") then
          overrides[fx.name] = nil
          dirty = true
        end
      end
    else
      r.ImGui_Text(ctx, "No FX selected.")
    end

    r.ImGui_EndChild(ctx)
  end

  r.ImGui_End(ctx)

  if open then
    r.defer(loop)
  else
    r.ImGui_DestroyContext(ctx)
  end
end

r.defer(loop)
