-- DF95_PluginMetaOverrides_Airwindows_JSFX.lua
--
-- Manuell kuratierte Kategorien für Airwindows- und JSFX-Plugins.
-- Diese Datei ist als Ergänzung zu den Auto-Overrides gedacht.

local M = {}
M.OVERRIDES = {
  ["VST3: Airwindows Consolidated (Airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ADClip7 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ADClip8 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ADT (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: AQuickVoiceClip (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Acceleration (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Acceleration2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Air (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Air2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Air3 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Air4 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: AngleEQ (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: Apicolypse (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: AtmosphereBuss (airwindows)"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["VST: AtmosphereChannel (airwindows)"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["VST: Aura (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: AutoPan (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: AverMatrix (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Average (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Balanced (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BassAmp (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: BassDrive (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BassKit (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: Baxandall (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Baxandall2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Beam (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BezEQ (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: BigAmp (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Biquad (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Biquad2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BiquadDouble (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BiquadHiLo (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BiquadNonLin (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BiquadOneHalf (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BiquadPlus (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BiquadStack (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BiquadTriple (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BitGlitter (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BitShiftGain (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BitShiftPan (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Bite (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BlockParty (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BrassRider (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BrightAmbience (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BrightAmbience2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BrightAmbience3 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BuildATPDF (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: BussColors4 (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: ButterComp (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ButterComp2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: C5RawBuss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: C5RawChannel (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: CStrip (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: CStrip2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Cabs (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Calibre (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Cans (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: CansAW (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Capacitor (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Capacitor2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Chamber (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: Chamber2 (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: Channel4 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Channel5 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Channel6 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Channel7 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Channel8 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Channel9 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Chorus (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ChorusEnsemble (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ChromeOxide (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Cider (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ClearCoat (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ClipOnly (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ClipOnly2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ClipSoftly (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: CloudCoat (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Coils (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Coils2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Cojones (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Compresaturator (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Console0Buss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console0Channel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console4Buss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console4Channel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console5Buss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console5Channel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console5DarkCh (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console6Buss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console6Channel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console7Buss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console7Cascade (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console7Channel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console7Crunch (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console8BussHype (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console8BussIn (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console8BussOut (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console8ChannelHype (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console8ChannelIn (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console8ChannelOut (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console8LiteBuss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console8LiteChannel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console8SubHype (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console8SubIn (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console8SubOut (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console9Buss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Console9Channel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: ConsoleLABuss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: ConsoleLAChannel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: ConsoleMCBuss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: ConsoleMCChannel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: ConsoleMDBuss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: ConsoleMDChannel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: ConsoleXBuss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: ConsoleXChannel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: ConsoleXPre (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: ContentHideD (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: CreamCoat (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Creature (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: CrickBass (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: CrunchCoat (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: CrunchyGrooveWear (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Crystal (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DCVoltage (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Dark (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DarkNoise (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DeBess (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DeEss (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DeHiss (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DeRez (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DeRez2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DeRez3 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Deckwrecka (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Density (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Density2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Desk (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Desk4 (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: DigitalBlack (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Dirt (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Discontinuity (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Disintegrate (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Distance (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Distance2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Distance3 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Distortion (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DitherFloat (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: DitherMeDiskers (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: DitherMeTimbers (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: Ditherbox (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: DoublePaul (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Doublelay (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Drive (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DrumSlam (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DubCenter (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DubPlate (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: DubPlate2 (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: DubSub (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DubSub2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Dubly (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Dubly2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Dubly3 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: DustBunny (airwindows)"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["VST: Dynamics (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Dyno (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: EQ (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: EdIsDim (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Edge (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Elation (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ElectroHat (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Elliptical (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Energy (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Energy2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Ensemble (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: EveryConsole (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: EverySlew (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: EveryTrim (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Exciter (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Facet (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: FathomFive (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: FinalClip (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: FireAmp (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Flipity (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Floor (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Flutter (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Flutter2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Focus (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Fracture (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Fracture2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: FromTape (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Galactic (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Galactic2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Galactic3 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: GalacticVibe (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Gatelope (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: GlitchShifter (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: GoldenSlew (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Golem (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: GrindAmp (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Gringer (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: GrooveWear (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: GuitarConditioner (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: HardVacuum (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: HermeTrim (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Hermepass (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: HighGlossDither (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: HighImpact (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Highpass (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: Highpass2 (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: Holt (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Holt2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Hombre (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Huge (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Hull (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Hull2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Hype (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Hypersoft (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: HypersonX (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Hypersonic (airwindows)"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["VST: Infinity (airwindows)"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["VST: Infinity2 (airwindows)"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["VST: Inflamer (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Infrasonic (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Interstage (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: IronOxide5 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: IronOxideClassic (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: IronOxideClassic2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Isolator (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Isolator2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Isolator3 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Kalman (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: LRConvolve (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: LRConvolve2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: LRFlipTimer (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: LeadAmp (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: LeftoMono (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: LilAmp (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Logical4 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Loud (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Lowpass (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: Lowpass2 (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: Luxor (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: MSFlipTimer (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: MV (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: MV2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: MackEQ (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: Mackity (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: Mastering (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: MatrixVerb (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: Melt (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: MidAmp (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: MidSide (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: MoNoam (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Mojo (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Monitoring (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: Monitoring2 (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: Monitoring3 (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: MultiBandDistortion (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: NC-17 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: NaturalizeDither (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: Neverland (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Nikola (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: NodeDither (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: Noise (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: NonlinearSpace (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: NotJustAnotherCD (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: NotJustAnotherDither (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: OneCornerClip (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: OrbitKick (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Overheads (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PDBuss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: PDChannel (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Pafnuty (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Pafnuty2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Parametric (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PaulDither (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: PaulWide (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PeaksOnly (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Pear (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Pear2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PhaseNudge (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PitchDelay (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PitchNasty (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PlatinumSlew (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PocketVerbs (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: Pockey (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Pockey2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Podcast (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PodcastDeluxe (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Point (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Pop (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Pop2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Pop3 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PowerSag (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PowerSag2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Precious (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Preponderant (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Pressure4 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Pressure5 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PurestAir (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PurestConsole2Buss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: PurestConsole2Channel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: PurestConsole3Buss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: PurestConsole3Channel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: PurestConsoleBuss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: PurestConsoleChannel (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: PurestDrive (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PurestEcho (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PurestFade (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PurestGain (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PurestSquish (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PurestWarm (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: PurestWarm2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Pyewacket (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: RawGlitters (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: RawTimbers (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Recurve (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Remap (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ResEQ (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: ResEQ2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Reverb (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: Righteous4 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: RightoMono (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: RingModulator (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: SampleDelay (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Shape (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ShortBuss (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: SideDull (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Sidepass (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Silhouette (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Sinew (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: SingleEndedTriode (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Slew (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Slew2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Slew3 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: SlewOnly (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: SlewSonic (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Smooth (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: SmoothEQ (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: SoftGate (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: SpatializeDither (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: Spiral (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Spiral2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: SquareRoot (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Srsly (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Srsly2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Srsly3 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: StarChild (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: StarChild2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: StereoChorus (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: StereoDoubler (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: StereoEnsemble (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: StereoFX (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: StoneFireComp (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: Stonefire (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: StudioTan (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: SubTight (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: SubsOnly (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Surge (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: SurgeTide (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Sweeten (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Swell (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: TPDFDither (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: TPDFWide (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Tape (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: TapeBias (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: TapeDelay (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: TapeDelay2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: TapeDither (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: TapeDust (airwindows)"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["VST: TapeFat (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Texturize (airwindows)"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["VST: TexturizeMS (airwindows)"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["VST: Thunder (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ToTape5 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ToTape6 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ToTape7 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ToTape8 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ToVinyl4 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ToneSlant (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: TransDesk (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: TremoSquare (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Tremolo (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Trianglizer (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: TripleSpread (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Tube (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Tube2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: TubeDesk (airwindows)"] = { category = "console_tape", idm_group = "IDM_BUSS" },
  ["VST: UltrasonX (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Ultrasonic (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: UltrasonicLite (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: UltrasonicMed (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: UnBox (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: VariMu (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Verbity (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: Verbity2 (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: Vibrato (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: VinylDither (airwindows)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["VST: VoiceOfTheStarship (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: VoiceTrick (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Weight (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Wider (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Wolfbot (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: XBandpass (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: XHighpass (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: XLowpass (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: XNotch (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: XRegion (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: YBandpass (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: YHighpass (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: YLowpass (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: YNotBandpass (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: YNotHighpass (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: YNotLowpass (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: YNotNotch (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: YNotch (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ZBandpass (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ZBandpass2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ZHighpass (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: ZHighpass2 (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: ZLowpass (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: ZLowpass2 (airwindows)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["VST: ZNotch (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ZNotch2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ZOutputStage (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ZRegion (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: ZRegion2 (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: Zoom (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: curve (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: kCathedral (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: kCathedral2 (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: kCathedral3 (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: kChamberAR (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: kGuitarHall (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: kPlate140 (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: kPlate240 (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: kPlateA (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: kPlateB (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: kPlateC (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: kPlateD (airwindows)"] = { category = "reverb", idm_group = "IDM_SPACE" },
  ["VST: uLawDecode (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["VST: uLawEncode (airwindows)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["JS: 1175 Compressor"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: 3-Band EQ"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: 3-Band Peak Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: 3x3 EQ"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: 3x3 EQ (1-Pole Crossover)"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: 4-Band EQ"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: 4-Tap Phaser"] = { category = "modulation", idm_group = "IDM_STEREO" },
  ["JS: 4x4 EQ"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: Apple 12-Pole Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: Apple 2-Pole Lowpass Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: Auto Expander"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Bit Meter (Cockos)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: Butterworth 4-Pole Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: Channel Phase Meter"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: Channel Time Delayer"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Chebyshev 4-Pole Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: Chorus"] = { category = "modulation", idm_group = "IDM_STEREO" },
  ["JS: Chorus (Improved Shaping)"] = { category = "modulation", idm_group = "IDM_STEREO" },
  ["JS: Chorus (Stereo)"] = { category = "modulation", idm_group = "IDM_STEREO" },
  ["JS: Compciter"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: DC Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: De-esser"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Delay"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Delay (Floaty)"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Delay (Lo-Fi)"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Delay w/Chorus"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Delay w/LFO-Modulated Length"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Delay w/Reverseness"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Delay w/Stereo Bounce"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Delay w/Sustain"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Delay w/Tempo Length"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Delay w/Tempo Ping-Pong"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Delay w/Tone Control"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Digital Drum Compressor"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Digital Versatile Compressor"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Digital Versatile Compressor v2"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Dirt Squeeze Compressor"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Distortion"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["JS: Distortion (Fuzz)"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["JS: Downward Expander"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Dynamic Range Meter"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: Event Horizon Clipper"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["JS: Event Horizon Limiter/Clipper"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Express Bus Compressor"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: FFT Peak-Following Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: FFT Splitter"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["JS: Fairly Childish Compressor/Limiter"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Fairly Childish Stereo Compressor/Limiter"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Flanger"] = { category = "modulation", idm_group = "IDM_STEREO" },
  ["JS: Frequency Spectrum Analyzer Meter (Cockos)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: Gain Reduction Scope (Cockos)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: Goniometer"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: Granular Loop Sampler"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["JS: Loudness Meter Peak/RMS/LUFS (Cockos)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: MDCT Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: MDCT Sweeping Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: MGA JS Limiter"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: MGA JS Limiter (Unlinked Stereo)"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: MIDI Delay"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: MIDI Duplicate Note Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: MIDI EQ Ducker"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: MIDI Note Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: MIDI Note Hold"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["JS: MIDI Note-On Delay"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: MIDI Velocity Scaler/Compressor"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Major Tom Compressor"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Master Limiter"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Master Tom Compressor"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Moog 4-Pole Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: NP1136 Peak Limiter"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Oscilloscope Meter (Cockos)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: Ozzifier Chorus"] = { category = "modulation", idm_group = "IDM_STEREO" },
  ["JS: Presence EQ"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: RBJ 1073 EQ"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: RBJ 12-Band EQ w/HPF"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: RBJ 4-Band Notch Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: RBJ 4-Band Semi-Parametric EQ"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: RBJ 4-Band Semi-Parametric EQ v2"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: RBJ 7-Band Graphic EQ"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: RBJ Highpass/Lowpass Filters"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: RBJ Stereo Image Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: Resonant Lowpass Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: SMPTE LTC Reader/Meter"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: Saturation"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["JS: Shelving Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: Simple 1-Pole Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: Simple Peak-1 Limiter"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Soft Clipper/Limiter"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Spectral Hold (Cockos)"] = { category = "texture_experimental", idm_group = "IDM_TEXTURE" },
  ["JS: Spectrograph Spectrogram Meter (Cockos)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: Spectropaint Filter"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: Spectropaint Synthesis"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: State Variable Morphing Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: Sweeping Resonant Lowpass Filter"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: Tilt Equalizer"] = { category = "filter_eq", idm_group = "IDM_TONE" },
  ["JS: Time Adjustment Delay"] = { category = "delay", idm_group = "IDM_ECHO" },
  ["JS: Tone Gate"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: Tremolo"] = { category = "modulation", idm_group = "IDM_STEREO" },
  ["JS: Upward Expander"] = { category = "dynamics", idm_group = "IDM_BUSS" },
  ["JS: VU Meter"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: VU Meter (Summed)"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: Waveshaping Distortion"] = { category = "saturation", idm_group = "IDM_GLITCH" },
  ["JS: WigWare Multi-channel Peak VU Meter"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
  ["JS: Zoom Analyzer Demo"] = { category = "meter_utility", idm_group = "IDM_UTILITY" },
}
return M