-- @description DF95: Build IFLS Main Toolbar MenuSet (v1.0.2 - correct ReaperMenuSet syntax)
-- @version 1.0.2
-- @author DF95 (generated by Reaper DAW Ultimate Assistant)
-- @about
--   FIX: Writes toolbar entries in reaper-menu.ini / ReaperMenuSet syntax:
--     item_0=ACTION  LABEL
--     icon_0=text_wide
--   (Previous ACT/ITEM syntax gets imported but ignored by REAPER, leaving toolbar empty.)
--
--   Output:
--     REAPER\ResourcePath\MenuSets\IFLS_Main.Toolbar.ReaperMenuSet
--
--   Use:
--     Options > Customize menus/toolbars...
--     Select: Floating toolbar 1 (Toolbar 1)
--     Import/Export > Import...
--     Choose: IFLS_Main.Toolbar.ReaperMenuSet
--
--   Notes:
--   - Registers referenced scripts as actions to obtain valid _RS... command IDs.
--   - If a script is missing, its button will be written inert as item_N=-1 <Missing...>

local function msg(s) reaper.ShowConsoleMsg(tostring(s) .. "\n") end
local function join(a,b)
  if not a or a=="" then return b end
  local last=a:sub(-1)
  if last=="\\" or last=="/" then return a..b end
  return a.."/"..b
end
local function exists(path)
  local f=io.open(path,"rb")
  if f then f:close(); return true end
  return false
end
local function ensure_dir(path) reaper.RecursiveCreateDirectory(path,0) end

local function ensure_named_command(script_abs_path, sectionID)
  if not exists(script_abs_path) then return nil, "missing: "..script_abs_path end
  local cmdID = reaper.AddRemoveReaScript(true, sectionID, script_abs_path, true)
  if not cmdID or cmdID == 0 then
    return nil, "AddRemoveReaScript failed for: "..script_abs_path
  end
  local name = reaper.ReverseNamedCommandLookup(cmdID)
  if not name or name == "" then
    return nil, "ReverseNamedCommandLookup failed for cmdID="..tostring(cmdID)
  end
  return "_"..name, nil
end

-- CONFIG
local resource = reaper.GetResourcePath()
local scripts_root = join(resource, "Scripts")
local SECTION_MAIN = 0

local buttons = {
  {label="IFLS Beat Control Center", script_rel="IFLS/IFLS/Hubs/IFLS_BeatControlCenter_ImGui.lua"},
  {label="IFLS Artist Hub",         script_rel="IFLS/IFLS/Hubs/IFLS_ArtistHub_ImGui.lua"},
  {label="IFLS SampleGalaxy",       script_rel="IFLS/IFLS/Hubs/IFLS_SampleLibraryHub_ImGui.lua"},
  {label="IFLS Groove & Rhythm",    script_rel="IFLS/IFLS/Hubs/IFLS_PolyRhythmHub_ImGui.lua"},
  {label="IFLS Macros & Scenes",    script_rel="IFLS/IFLS/Hubs/IFLS_SceneHub_ImGui.lua"},
  {label="IFLS FX Brain",           script_rel="IFLS/IFLS/Hubs/IFLS_MasterHub_ImGui.lua"},
  {label="IFLS Diagnostics / Inspector", script_rel="IFLS/DF95/DF95_Diagnostics_Insight_Run.lua"},
  {label="IFLS Dev / Debug",        script_rel="IFLS/IFLS/Domain/IFLS_Diagnostics_DebugDemo.lua"},
}

reaper.ClearConsole()
msg("DF95: Build IFLS Main Toolbar MenuSet (v1.0.2 - correct syntax)")
msg("ResourcePath: "..resource)

local resolved={}
local ok_count, miss_count = 0, 0
for i,b in ipairs(buttons) do
  local abs = join(scripts_root, b.script_rel)
  local named, err = ensure_named_command(abs, SECTION_MAIN)
  if named then
    ok_count=ok_count+1
    resolved[#resolved+1]={idx=i-1, cmd=named, label=b.label, missing=false}
    msg(("  OK   %d: %s -> %s"):format(i-1, b.label, named))
  else
    miss_count=miss_count+1
    resolved[#resolved+1]={idx=i-1, cmd="-1", label="MISSING: "..b.label, missing=true, err=tostring(err)}
    msg(("  MISS %d: %s (%s)"):format(i-1, b.label, tostring(err)))
  end
end

local menuSets = join(resource, "MenuSets")
ensure_dir(menuSets)
local out_path = join(menuSets, "IFLS_Main.Toolbar.ReaperMenuSet")

-- IMPORTANT: keep ASCII/UTF-8 without BOM. REAPER may ignore first toolbar if BOM/Unicode weirdness exists.
local f=assert(io.open(out_path,"wb"))
f:write("; DF95/IFLS - IFLS Main Toolbar (generated)\n")
f:write("; Toolbar syntax: item_N=ACTION  LABEL, icon_N=text_wide\n")
f:write("; Import into: Options > Customize menus/toolbars... > Floating toolbar 1 (Toolbar 1) > Import...\n\n")

-- Exact allowed header per REAPER (see reaper-menu.ini rules)
f:write("[Floating toolbar 1 (Toolbar 1)]\n")
f:write("title=IFLS Main\n")

for _,it in ipairs(resolved) do
  -- Use text_wide so you see labels even without icons
  f:write(("icon_%d=text_wide\n"):format(it.idx))
  if it.missing then
    -- non-clickable "separator/label" style if missing
    f:write(("item_%d=-1 %s\n"):format(it.idx, it.label))
  else
    f:write(("item_%d=%s %s\n"):format(it.idx, it.cmd, it.label))
  end
end

f:write("\n")
f:close()

msg("")
msg("Wrote: "..out_path)
msg(("Resolved: %d OK, %d missing"):format(ok_count, miss_count))
msg("NEXT: Customize menus/toolbars > Floating toolbar 1 (Toolbar 1) > Import/Export > Import > IFLS_Main.Toolbar.ReaperMenuSet")
