-- @description DF95 Toolbar Suite - Legacy Compatibility (optional)
-- @version 1.0.0
-- @author DF95
-- @metapackage
-- @about
--   OPTIONAL compatibility layer for older DF95 installs.
--   Use ONLY if you previously published scripts under different target paths.
--   Put stub/tombstone scripts under _payload/Legacy/ and keep old entry points alive.
--
-- @provides
--   Legacy/** > Scripts/DF95_Legacy/
