name: ReaPack check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - run: gem install reapack-index

      # check Modus (Validierung)
      - run: reapack-index -c _payload --no-progress
