-- IFLS_Contracts.lua
-- Core contract definitions for IFLS (formerly DF95) system.
-- Centralizes ExtState namespaces and keys.

local M = {}

M.NS_BEAT    = "DF95_AI_BEAT"
M.NS_BEAT_CC = "DF95_BEAT_CC"
M.NS_SAMPLEDB = "DF95_SAMPLEDB"
M.NS_ARTIST   = "DF95_ARTIST"
M.NS_DEVTOOLS = "DF95_DEVTOOLS"

M.BEAT_KEYS = {
  BPM      = "BPM",
  TS_NUM   = "TS_NUM",
  TS_DEN   = "TS_DEN",
  BARS     = "BARS",
  MODE     = "MODE",
  SWING    = "SWING",
  GROOVE   = "GROOVE",
}

M.BEAT_CC_KEYS = {
  ENGINE             = "ENGINE",
  USE_MIDI_LAYERS    = "USE_MIDI_LAYERS",
  USE_LOOP_LAYERS    = "USE_LOOP_LAYERS",
  USE_SPEECH_LAYERS  = "USE_SPEECH_LAYERS",
  USE_SAMPLER_SETUP  = "USE_SAMPLER_SETUP",
  SAMPLER_MODE       = "SAMPLER_MODE",
  ARTIST_PROFILE     = "ARTIST_PROFILE",
  SAMPLEDB_FILTER    = "SAMPLEDB_FILTER",
  SAMPLEDB_CATEGORY  = "SAMPLEDB_CATEGORY",
  HUMANIZE_MODE      = "HUMANIZE_MODE",
  REROLL_REQUEST     = "REROLL_REQUEST",
  -- Phase 77: IDM FX chain options
  IDM_CHAIN_PROFILE  = "IDM_CHAIN_PROFILE",
  IDM_CHAIN_AUTOFX   = "IDM_CHAIN_AUTOFX",
}

M.ARTIST_KEYS = {
  CURRENT_ARTIST      = "CURRENT_ARTIST",
  STYLE_PRESET        = "STYLE_PRESET",
  HUMANIZE_DEPTH      = "HUMANIZE_DEPTH",
  MICROTIMING_VARIANT = "MICROTIMING_VARIANT",
}

M.SAMPLEDB_KEYS = {
  ACTIVE_LIBRARY     = "ACTIVE_LIBRARY",
  TAG_FILTER         = "TAG_FILTER",
  LOOP_TAG           = "LOOP_TAG",
  SPEECH_TAG         = "SPEECH_TAG",
  LAST_SELECTION     = "LAST_SELECTION",
}

M.DEVTOOLS_KEYS = {
  SAFE_TEST_LAST_RUN = "SAFE_TEST_LAST_RUN",
  SAFE_TEST_STATUS   = "SAFE_TEST_STATUS",
}

return M
