-- @description DF95 Toolbar Suite - Core
-- @version 1.0.0
-- @author DF95
-- @metapackage
-- @about
--   Installs the DF95 core scripts + resources.
--   STABILITY CONTRACT (do not break):
--   1) Do not move/rename THIS package file once published.
--   2) Do not change the TARGET install paths (right side of ' > ') once published.
--   3) Refactors must happen only inside _payload/ while keeping these mappings stable.
--
-- @provides
--   _payload/Scripts/** > Scripts/
--   _payload/DF95_MetaCore/** > DF95_MetaCore/
--
--   _payload/Data/** > Data/
--   _payload/Config/** > Config/
--   _payload/Effects/** > Effects/
--   _payload/FXChains/** > FXChains/
--   _payload/Chains/** > Chains/
--   _payload/TrackTemplates/** > TrackTemplates/
--   _payload/RenderPresets/** > RenderPresets/
--   _payload/Projects/** > Projects/
--   _payload/Theme/** > Theme/
--   _payload/ThemeMod/** > ThemeMod/
--   _payload/Reports/** > Reports/
--   _payload/Support/** > Support/
--   _payload/_selectors/** > _selectors/
--   _payload/tools/** > tools/
